version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "finny"
  api:
    image: finnyapp/finny-api
    command: java -jar app-standalone.jar
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres@db:5432/finny"
  test:
    image: finnyapp/finny-api
    command: lein unit-tests
    environment:
      FINNY_ENV: 'test'
  tests-with-db:
    image: finnyapp/finny-api
    command: lein do migratus migrate, midje
    environment:
      DATABASE_URL: "postgres://postgres@db:5432/finny"
    depends_on:
      - db
